/**
 * The IPC contract (§6.8), mirrored from `crates/fruit-core/src/model.rs`.
 *
 * In a build that can link a webview these are generated by `tauri-specta`, so
 * the contract is compile-time checked on both sides. Until then they are
 * maintained by hand and guarded by `npm run check:contract`, which diffs the
 * field names against the Rust structs.
 *
 * The renderer holds no SQL and no business logic. Anything derived — drift,
 * drift state, groupings, takeaway lines — arrives already computed.
 */

export type Millis = number;
export type LocalDate = string; // 'YYYY-MM-DD', local
export type Status = "open" | "done" | "cancelled";

export interface TagRow {
  id: string;
  name: string;
  colour: string | null;
}

export interface ProjectRow {
  id: string;
  name: string;
  colour: string;
  icon: string | null;
  kind: string;
  sortRank: number;
  isArchived: boolean;
  weeklyTargetSec: number | null;
  openTaskCount: number;
  weekTrackedSec: number;
  createdAt: Millis;
  updatedAt: Millis;
}

export interface TaskRow {
  id: string;
  projectId: string | null;
  parentId: string | null;
  title: string;
  status: Status;
  estimateSec: number | null;
  dueDate: LocalDate | null;
  dueAt: Millis | null;
  priority: number;
  energy: string | null;
  /** "Doesn't fit one sitting" — the top of the estimate scale, and a distinct
   *  state from "not estimated yet". */
  isRollover: boolean;
  sortRank: number;
  completedAt: Millis | null;
  tags: TagRow[];
  trackedSec: number;
  subtaskTotal: number;
  subtaskDone: number;
  isScheduled: boolean;
  /** When work was first and last recorded against this task, from its sessions. */
  firstSessionAt: Millis | null;
  lastSessionAt: Millis | null;
  createdAt: Millis;
  updatedAt: Millis;
}

export interface BlockRow {
  id: string;
  taskId: string | null;
  label: string | null;
  startsAt: Millis;
  durationSec: number;
  localDate: LocalDate;
  tz: string;
  isFixed: boolean;
  createdAt: Millis;
  updatedAt: Millis;
}

export interface SessionRow {
  id: string;
  taskId: string;
  taskTitle: string;
  blockId: string | null;
  startedAt: Millis;
  endedAt: Millis | null;
  elapsedSec: number;
  heartbeatAt: Millis | null;
  source: "timer" | "pomodoro" | "manual" | "recovered";
  isConfirmed: boolean;
  note: string | null;
}

/** §5.6 redundancy table. No drift state is carried by colour alone. */
export type DriftState =
  | "notStarted"
  | "inProgress"
  | "onEstimate"
  | "overrun"
  | "underrunPast";

export interface BlockView {
  block: BlockRow;
  title: string;
  projectId: string | null;
  projectColour: string | null;
  taskStatus: Status | null;
  plannedSec: number;
  trackedSec: number;
  driftSec: number;
  driftState: DriftState;
  isRunning: boolean;
  lane: number;
  lanes: number;
}

export interface DayColumn {
  localDate: LocalDate;
  isToday: boolean;
  isPast: boolean;
  blocks: BlockView[];
  plannedSec: number;
  trackedSec: number;
  unplannedSec: number;
  isReconciled: boolean;
}

export interface WeekView {
  from: LocalDate;
  to: LocalDate;
  tz: string;
  days: DayColumn[];
  /** Server-side now, so the cursor never depends on a skewed renderer clock. */
  now: Millis;
}

export interface TaskDetail {
  task: TaskRow;
  note: string;
  noteUpdatedAt: Millis | null;
  sessions: SessionRow[];
  subtasks: TaskRow[];
  blocks: BlockRow[];
  project: ProjectRow | null;
}

export interface TaskGroup {
  key: string;
  label: string;
  count: number;
  estimateSec: number;
  taskIds: string[];
}

export interface BacklogView {
  groups: TaskGroup[];
  tasks: TaskRow[];
}

export interface Page<T> {
  rows: T[];
  total: number;
}

export type TimerPhase = "idle" | "running" | "idleChallenge" | "break" | "recovering";
export type PomodoroPhase = "work" | "shortBreak" | "longBreak";

export interface PomodoroState {
  phase: PomodoroPhase;
  cycle: number;
  cyclesBeforeLong: number;
  phaseEndsAt: Millis;
}

export interface TimerState {
  phase: TimerPhase;
  /** The task being timed. Outlives any one segment, so it survives an idle gap. */
  runTaskId: string | null;
  taskTitle: string | null;
  /** The open segment, or null during an idle challenge or break. */
  session: SessionRow | null;
  /** Counted seconds for the whole run, across segments. */
  elapsedSec: number;
  /** Counted seconds for the open segment only. */
  segmentElapsedSec: number;
  idleFrom: Millis | null;
  idleTo: Millis | null;
  recoverySessionId: string | null;
  pomodoro: PomodoroState | null;
}

export type ReconcileKind =
  | "overran"
  | "neverStarted"
  | "untrackedGap"
  | "unplannedSession";

export type ReconcileVerb =
  | "accept"
  | "rescheduleRemainder"
  | "split"
  | "drop"
  | "markDone"
  | "reviseEstimate"
  | "moveToTomorrow"
  | "leaveUnscheduled"
  | "createRetroBlock"
  | "assignToTask"
  | "logAsBreak"
  | "ignore";

export interface ReconcileItem {
  id: string;
  kind: ReconcileKind;
  title: string;
  blockId: string | null;
  taskId: string | null;
  sessionId: string | null;
  plannedSec: number;
  trackedSec: number;
  driftSec: number;
  startsAt: Millis | null;
  endsAt: Millis | null;
  defaultAction: ReconcileVerb;
  available: ReconcileVerb[];
  suggestedSlot: Millis | null;
  suggestedDurationSec: number;
}

export interface ReconcileAction {
  itemId: string;
  verb: ReconcileVerb;
  startsAt?: Millis | null;
  durationSec?: number | null;
  taskId?: string | null;
  estimateSec?: number | null;
}

export interface DayReview {
  localDate: LocalDate;
  reconciledAt: Millis;
  plannedSec: number;
  trackedSec: number;
  overrunSec: number;
  unplannedSec: number;
  blocksTotal: number;
  blocksUntouched: number;
  calibrationRatio: number | null;
  takeaway: string;
}

export interface CalibrationBucket {
  bucket: string;
  n: number;
  medianRatio: number;
  isReportable: boolean;
}

export interface CalibrationReport {
  overallMedian: number | null;
  sampleCount: number;
  buckets: CalibrationBucket[];
  headline: string;
  worstBucket: string | null;
}

export interface ProjectWeekRow {
  projectId: string | null;
  projectName: string;
  projectColour: string;
  weekStart: LocalDate;
  plannedSec: number;
  trackedSec: number;
}

export interface WeeklyTargetRow {
  projectId: string;
  projectName: string;
  projectColour: string;
  targetSec: number;
  trackedSec: number;
  paceSec: number;
}

export interface ReportBundle {
  from: LocalDate;
  to: LocalDate;
  calibration: CalibrationReport;
  projectWeeks: ProjectWeekRow[];
  weeklyTargets: WeeklyTargetRow[];
  totalPlannedSec: number;
  totalTrackedSec: number;
  streakDays: number;
}

export interface SearchHit {
  kind: string;
  id: string;
  title: string;
  subtitle: string | null;
  matchFrom: number | null;
  matchTo: number | null;
}

export interface SearchResults {
  query: string;
  hits: SearchHit[];
}

export interface UndoToken {
  entity: string;
  id: string;
  label: string;
  at: Millis;
}

export interface DeletedRow {
  entity: string;
  id: string;
  title: string;
  deletedAt: Millis;
}

export interface CaptureChip {
  kind: "project" | "tag" | "estimate" | "priority" | "due";
  raw: string;
  display: string;
  from: number;
  to: number;
  /** §4.4 rule 7 — an unknown project renders as `#newproj (create)`. */
  creates: boolean;
}

export interface CapturePreview {
  raw: string;
  title: string;
  projectName: string | null;
  projectId: string | null;
  projectCreates: boolean;
  tags: string[];
  estimateSec: number | null;
  priority: number;
  dueDate: LocalDate | null;
  dueAt: Millis | null;
  chips: CaptureChip[];
}

export interface IntegrityReport {
  quickCheck: string;
  foreignKeyViolations: number;
  orphanOpenSessions: number;
  cachesRepaired: number;
  blocksCrossingMidnight: number;
  pageCount: number;
  dbBytes: number;
  checkedAt: Millis;
}

export type CollisionPolicy = "overlap" | "push" | "shrink";
export type IdleActionKind = "keep" | "discard" | "assignToBreak";
export type RecoveryActionKind = "trimToHeartbeat" | "keepAll" | "discard";

/** Errors cross IPC as `{ code, message }` — branch on the code, show the sentence. */
export interface WireError {
  code: string;
  message: string;
}

export interface NewTask {
  title: string;
  projectId?: string | null;
  parentId?: string | null;
  estimateSec?: number | null;
  dueDate?: LocalDate | null;
  dueAt?: Millis | null;
  priority?: number | null;
  energy?: string | null;
  isRollover?: boolean;
  tags?: string[];
}

export interface TaskPatch {
  title?: string;
  projectId?: string | null;
  estimateSec?: number | null;
  dueDate?: LocalDate | null;
  dueAt?: Millis | null;
  priority?: number;
  energy?: string | null;
  sortRank?: number;
  isRollover?: boolean;
  tags?: string[];
}

export interface NewBlock {
  taskId?: string | null;
  label?: string | null;
  startsAt: Millis;
  durationSec: number;
  tz: string;
  isFixed?: boolean;
}

export interface TaskQuery {
  projectId?: string | null;
  tag?: string | null;
  text?: string | null;
  scope?: "open" | "done" | "all" | "deleted";
  includeSubtasks?: boolean;
  limit?: number;
  offset?: number;
}
