/**
 * The IPC contract (§6.8), mirrored from `crates/fruit-core/src/model.rs`.
 *
 * In a build that can link a webview these are generated by `tauri-specta`, so
 * the contract is compile-time checked on both sides. Until then they are
 * maintained by hand and guarded by `npm run check:contract`, which diffs the
 * field names against the Rust structs.
 *
 * The renderer holds no SQL and no business logic. Anything derived — drift,
 * drift state, groupings, takeaway lines — arrives already computed.
 */

export type Millis = number;
export type LocalDate = string; // 'YYYY-MM-DD', local
export type Status = "open" | "done" | "cancelled";

export interface TagRow {
  id: string;
  name: string;
  colour: string | null;
}

export interface ProjectRow {
  id: string;
  name: string;
  colour: string;
  icon: string | null;
  kind: string;
  sortRank: number;
  isArchived: boolean;
  weeklyTargetSec: number | null;
  openTaskCount: number;
  weekTrackedSec: number;
  createdAt: Millis;
  updatedAt: Millis;
}

export interface TaskRow {
  id: string;
  projectId: string | null;
  parentId: string | null;
  title: string;
  status: Status;
  estimateSec: number | null;
  dueDate: LocalDate | null;
  dueAt: Millis | null;
  priority: number;
  energy: string | null;
  /** "Doesn't fit one sitting" — the top of the estimate scale, and a distinct
   *  state from "not estimated yet". */
  isRollover: boolean;
  sortRank: number;
  completedAt: Millis | null;
  tags: TagRow[];
  trackedSec: number;
  subtaskTotal: number;
  subtaskDone: number;
  isScheduled: boolean;
  /** When work was first and last recorded against this task, from its sessions. */
  firstSessionAt: Millis | null;
  lastSessionAt: Millis | null;
  createdAt: Millis;
  updatedAt: Millis;
}

export interface BlockRow {
  id: string;
  taskId: string | null;
  label: string | null;
  startsAt: Millis;
  durationSec: number;
  localDate: LocalDate;
  tz: string;
  isFixed: boolean;
  /** Set on every instance of a repeating series (§2.3, P2). */
  seriesId: string | null;
  /** The rule itself, carried by the seed instance. */
  rrule: string | null;
  /** The VEVENT UID when this block came from a `.ics` file. */
  externalUid: string | null;
  /** What the interval was plotted *for* (migration 0009). */
  intent: BlockIntent;
  createdAt: Millis;
  updatedAt: Millis;
}

/**
 * What a plotted interval was for.
 *
 * An evening blocked out for a film is a plan for an interval, which is what a
 * block already is — so this is a property of the block rather than a second
 * kind of thing the planner has to draw.
 */
export type BlockIntent = "work" | "entertainment" | "life";

/** Which occurrences an edit to a series applies to. */
export type SeriesScope = "instance" | "future" | "all";

/**
 * A repeat preset, described by the same Rust that parses it. The renderer
 * holds no list of its own — a second list drifts, and the day it disagrees
 * the picker offers a rule the engine refuses.
 */
export interface RrulePreset {
  label: string;
  rrule: string;
  description: string;
}

// ─── activity (§3.5, P2) ───────────────────────────────────────────────

export type ActivitySupport = "full" | "impossible" | "notImplemented";

export interface ActivitySettings {
  enabled: boolean;
  /** Separate from `enabled`, and off even when apps are on. */
  titlesEnabled: boolean;
  /** The browser connector. Its own switch, for the same reason titles are. */
  domainsEnabled: boolean;
  paused: boolean;
  excludedApps: string[];
  /** Registrable domains. An entry covers every subdomain of itself. */
  excludedDomains: string[];
  excludedTitlePatterns: string[];
  /** 30 / 90 / 0 for forever. */
  retentionDays: number;
  /** Observation shorter than this is not reported. 0 disables the floor. */
  minSpanSec: number;
  nextPurgeAt: Millis | null;
}

export interface ActivityStatus {
  support: ActivitySupport;
  /** Why this platform can or cannot do it — always shown, never implied. */
  supportNote: string;
  settings: ActivitySettings;
}

// ─── browser connector (Plan Rev 3 §5.4) ───────────────────────────────

/** Three values, not `AreaKind`'s four: no domain implies rest. */
export type DomainCategory = "core" | "entertainment" | "other";

/**
 * A label the user can put on observed time — Work, Study, Distraction, Life,
 * and any they add.
 *
 * `countsAs` is the roll-up every report written before this feature reads, so
 * adding a category can never move a number that was already on screen.
 */
export interface ObservationCategory {
  id: string;
  name: string;
  colour: string;
  countsAs: DomainCategory;
  isBuiltin: boolean;
  sortRank: number;
  /** Observed seconds over whatever range was asked for; 0 if none was. */
  seconds: number;
}

/** Built-in category ids, fixed in migration 0007. */
export const CATEGORY = {
  work: "00000000-0000-7000-8000-000000000001",
  study: "00000000-0000-7000-8000-000000000002",
  distraction: "00000000-0000-7000-8000-000000000003",
  life: "00000000-0000-7000-8000-000000000004",
  other: "00000000-0000-7000-8000-000000000005",
} as const;

export type MatchKind = "app" | "domain";

export interface ActivityRule {
  id: string;
  matchKind: MatchKind;
  matchValue: string;
  categoryId: string;
  categoryName: string;
  categoryColour: string;
  /** Shipped with the app. Editing one makes it yours. */
  isBuiltin: boolean;
  /**
   * How many already-recorded but unlabelled stretches this rule just filled
   * in. Only meaningful on the row returned by `setActivityRule`; 0 when
   * listing.
   */
  backfilled: number;
}

/**
 * One continuous stretch of observation, as a thing you can point at.
 *
 * The aggregate answers "what should this *always* be"; this answers "what was
 * *that*". Different verbs — a rule and a relabel.
 */
export interface ObservedInterval {
  id: number;
  startedAt: Millis;
  endedAt: Millis;
  seconds: number;
  appId: string;
  domain: string | null;
  /** The video, the document, the ticket. Only when window titles are on. */
  windowTitle: string | null;
  categoryId: string | null;
}

/** Something observed that no rule covers, ranked by how much time it took. */
export interface UnlabelledRow {
  matchKind: MatchKind;
  matchValue: string;
  seconds: number;
  /** One 4-hour stretch and forty 6-minute ones are different problems. */
  occurrences: number;
  /** Longest first, so each can be labelled without committing to a rule. */
  stretches: ObservedInterval[];
}

// ─── notices (W4/W5) ───────────────────────────────────────────────────

export type NoticeKind = "focusElapsed" | "continuousWork" | "dailyCeiling" | "offPlan";

export interface Notice {
  kind: NoticeKind;
  /** Identifies the crossing, not the notice. */
  key: string;
  title: string;
  body: string;
}

// ─── weekly goals (PLAN-WEEKLY-GOALS.md W1/W2) ─────────────────────────

export type GoalSubject = "metric" | "lifeArea" | "project" | "category";

/** The whole-day quantities a goal can be set against. */
export const METRIC = {
  allWork: "allWork",
  life: "life",
  sleep: "sleep",
  entertainment: "entertainment",
  unaccounted: "unaccounted",
} as const;

/**
 * First-class, not a sign convention. "At most 5h of entertainment" is a goal
 * you succeed at by being under it.
 */
export type GoalDirection = "atLeast" | "atMost";

export interface GoalRow {
  id: string;
  subjectKind: GoalSubject;
  subjectId: string;
  /** Resolved in Rust — the renderer never looks a name up. */
  subjectName: string;
  direction: GoalDirection;
  targetSec: number;
  /** Bitmask, Monday = 1 … Sunday = 64. */
  appliesDays: number;
  startsWeek: string;
  endsWeek: string | null;
}

export interface NewGoal {
  subjectKind?: GoalSubject;
  subjectId: string;
  direction?: GoalDirection;
  targetSec: number;
  appliesDays?: number | null;
}

export type GoalState = "met" | "onPace" | "behind" | "atRisk" | "over";

export interface GoalProgress {
  goal: GoalRow;
  actualSec: number;
  /** The future is never a shortfall — Monday morning expects nothing. */
  expectedSec: number;
  /** Positive is good in both directions: ahead of pace, or under budget. */
  deltaSec: number;
  state: GoalState;
  /** The row that changes behaviour. `null` once the week is out of days. */
  perDayNeededSec: number | null;
  applicableDays: number;
  daysLeft: number;
  /** Built in Rust, because it differs by direction *and* by state. */
  summary: string;
}

/**
 * How broken up the work was — the components, deliberately **not** a score.
 *
 * A weighted 0–100 would be the one number in this app nobody could verify.
 * And `plannedSwitches` is something an app that only watches window focus
 * structurally cannot produce: a switch on a block boundary is you executing
 * your intention, not an interruption.
 */
export interface Fragmentation {
  longestStretchSec: number;
  stretches: number;
  plannedSwitches: number;
  unplannedSwitches: number;
  fragmentedSec: number;
  /** Rides along so the figure is never readable without its rule. */
  fragmentThresholdSec: number;
}

/** Offered, never applied. Trailing median, n ≥ 5. */
export interface GoalCalibration {
  goalId: string;
  /** So applying the suggestion is `setGoal` on the same quantity. */
  subjectKind: GoalSubject;
  subjectId: string;
  direction: GoalDirection;
  subjectName: string;
  targetSec: number;
  medianSec: number;
  weeks: number;
  weeksMet: number;
  suggestedSec: number;
  summary: string;
}

/** A goal Fruit will suggest, with the number it picked and where it came from. */
export interface GoalTemplate {
  key: string;
  name: string;
  subjectKind: GoalSubject;
  subjectId: string;
  direction: GoalDirection;
  /** `null` when there is not enough history to pick honestly. */
  targetSec: number | null;
  appliesDays: number;
  rationale: string;
}

export interface WeekReview {
  week: string;
  from: LocalDate;
  to: LocalDate;
  tz: string;
  totals: DayTotals;
  days: MonthDay[];
  elapsedSec: number;
  elapsedEmptySec: number;
  unreconciledDays: number;
  goals: GoalProgress[];
  fragmentation: Fragmentation;
  previousFragmentation: Fragmentation;
  calibration: GoalCalibration[];
}

export interface DomainTotal {
  domain: string;
  /** `null` when no rule covered it — a question, not a failure. */
  categoryId: string | null;
  categoryName: string | null;
  categoryColour: string | null;
  seconds: number;
}

export interface ConnectorStatus {
  enabled: boolean;
  hostManifestName: string;
  extensionDir: string;
  exePath: string;
  /** Bytes queued by the host and not yet drained. */
  queuedSamples: number;
}

export interface ActivitySpanRow {
  id: number;
  startedAt: Millis;
  endedAt: Millis;
  appId: string;
  windowTitle: string | null;
  /** The site, where the connector saw one. What the row is named after. */
  domain: string | null;
  /** The label in force when this was written. `null` is unlabelled. */
  categoryId: string | null;
}

export interface AppTotal {
  appId: string;
  seconds: number;
}

export interface BlockCorrelation {
  blockId: string;
  title: string;
  startsAt: Millis;
  durationSec: number;
  topApps: AppTotal[];
}

export interface ActivityDay {
  localDate: LocalDate;
  spans: ActivitySpanRow[];
  byApp: AppTotal[];
  correlations: BlockCorrelation[];
  trackedSec: number;
}

export interface IcsImportSummary {
  imported: number;
  updated: number;
  recurringInstances: number;
  skipped: number;
  note: string;
}

export interface SessionRow {
  id: string;
  taskId: string;
  taskTitle: string;
  blockId: string | null;
  startedAt: Millis;
  endedAt: Millis | null;
  elapsedSec: number;
  heartbeatAt: Millis | null;
  source: "timer" | "pomodoro" | "manual" | "recovered";
  isConfirmed: boolean;
  note: string | null;
  /** Work contribution mode. Work records only — life entries have no such field. */
  contribution: Contribution | null;
}

/** §5.6 redundancy table. No drift state is carried by colour alone. */
export type DriftState =
  | "notStarted"
  | "inProgress"
  | "onEstimate"
  | "overrun"
  | "underrunPast";

export interface BlockView {
  block: BlockRow;
  title: string;
  projectId: string | null;
  projectColour: string | null;
  taskStatus: Status | null;
  plannedSec: number;
  trackedSec: number;
  driftSec: number;
  driftState: DriftState;
  isRunning: boolean;
  lane: number;
  lanes: number;
}

export interface DayColumn {
  localDate: LocalDate;
  isToday: boolean;
  isPast: boolean;
  blocks: BlockView[];
  plannedSec: number;
  trackedSec: number;
  unplannedSec: number;
  isReconciled: boolean;
}

export interface WeekView {
  from: LocalDate;
  to: LocalDate;
  tz: string;
  days: DayColumn[];
  /** Server-side now, so the cursor never depends on a skewed renderer clock. */
  now: Millis;
}

export interface TaskDetail {
  task: TaskRow;
  note: string;
  noteUpdatedAt: Millis | null;
  sessions: SessionRow[];
  subtasks: TaskRow[];
  blocks: BlockRow[];
  project: ProjectRow | null;
}

export interface TaskGroup {
  key: string;
  label: string;
  count: number;
  estimateSec: number;
  taskIds: string[];
}

export interface BacklogView {
  groups: TaskGroup[];
  tasks: TaskRow[];
}

export interface Page<T> {
  rows: T[];
  total: number;
}

export type TimerPhase = "idle" | "running" | "idleChallenge" | "break" | "recovering";
export type PomodoroPhase = "work" | "shortBreak" | "longBreak";

export interface PomodoroState {
  phase: PomodoroPhase;
  cycle: number;
  cyclesBeforeLong: number;
  phaseEndsAt: Millis;
}

export interface TimerState {
  phase: TimerPhase;
  /** The task being timed. Outlives any one segment, so it survives an idle gap. */
  runTaskId: string | null;
  taskTitle: string | null;
  /** The open segment, or null during an idle challenge or break. */
  session: SessionRow | null;
  /** Counted seconds for the whole run, across segments. */
  elapsedSec: number;
  /** Counted seconds for the open segment only. */
  segmentElapsedSec: number;
  idleFrom: Millis | null;
  idleTo: Millis | null;
  recoverySessionId: string | null;
  pomodoro: PomodoroState | null;
  /**
   * When a focus session's intended length runs out (W3).
   *
   * Advisory, never enforcing: nothing stops, and going past it shows in drift
   * as the overrun it is.
   */
  focusEndsAt: Millis | null;
}

export type ReconcileKind =
  | "overran"
  | "neverStarted"
  | "untrackedGap"
  | "unplannedSession"
  /** The machine saw something and nobody said what it was (M10). */
  | "observedOnly"
  /** An hour with no record and no observation at all (M10). */
  | "empty";

export type ReconcileVerb =
  | "accept"
  | "rescheduleRemainder"
  | "split"
  | "drop"
  | "markDone"
  | "reviseEstimate"
  | "moveToTomorrow"
  | "leaveUnscheduled"
  | "createRetroBlock"
  | "assignToTask"
  | "logAsBreak"
  | "ignore"
  /** Confirm an interval as life time in a named area. */
  | "recordAsLife"
  /** Accounted for on purpose, nothing recorded about it. */
  | "markPrivate";

/**
 * Where a machine's claim came from. Only observed items carry this — they are
 * the only ones asking the user to accept an assertion they did not make.
 */
export interface ReconcileEvidence {
  source: string;
  subject: string;
  confidence: string;
  adjacent: string[];
  /** The privacy promise, restated where it counts. */
  storage: string;
  /**
   * The registrable domain behind this claim, when the browser connector made
   * it. Present exactly when a prospective rule is possible — an application
   * name is not something durable enough to key a rule on.
   */
  domain: string | null;
}

export interface ReconcileItem {
  id: string;
  kind: ReconcileKind;
  title: string;
  blockId: string | null;
  taskId: string | null;
  sessionId: string | null;
  plannedSec: number;
  trackedSec: number;
  driftSec: number;
  startsAt: Millis | null;
  endsAt: Millis | null;
  defaultAction: ReconcileVerb;
  available: ReconcileVerb[];
  suggestedSlot: Millis | null;
  suggestedDurationSec: number;
  /** What this item is and why it is on the list. */
  explanation: string;
  /** Why the default verb is the default. Shown on the recommended choice. */
  recommendation: string | null;
  evidence: ReconcileEvidence | null;
}

export interface ReconcileAction {
  itemId: string;
  verb: ReconcileVerb;
  startsAt?: Millis | null;
  durationSec?: number | null;
  taskId?: string | null;
  estimateSec?: number | null;
  /** For `recordAsLife`. */
  lifeAreaId?: string | null;
  /**
   * "Apply my choice to future activity in this context." Set to the item's
   * domain to write a rule alongside the decision. Prospective only — days
   * already reconciled keep the verdict they were written with.
   */
  ruleForDomain?: string | null;
  /**
   * Which label the rule applies. Optional — when absent the verb decides, so
   * the checkbox alone is enough for the common case.
   */
  ruleCategoryId?: string | null;
}

export interface DayReview {
  localDate: LocalDate;
  reconciledAt: Millis;
  plannedSec: number;
  trackedSec: number;
  overrunSec: number;
  unplannedSec: number;
  blocksTotal: number;
  blocksUntouched: number;
  calibrationRatio: number | null;
  takeaway: string;
  /** Consecutive reconciled days including this one (§2.3). */
  streakDays: number;
}

export interface CalibrationBucket {
  bucket: string;
  n: number;
  medianRatio: number;
  isReportable: boolean;
}

export interface CalibrationReport {
  overallMedian: number | null;
  sampleCount: number;
  buckets: CalibrationBucket[];
  headline: string;
  worstBucket: string | null;
}

export interface ProjectWeekRow {
  projectId: string | null;
  projectName: string;
  projectColour: string;
  weekStart: LocalDate;
  plannedSec: number;
  trackedSec: number;
}

export interface WeeklyTargetRow {
  projectId: string;
  projectName: string;
  projectColour: string;
  targetSec: number;
  trackedSec: number;
  paceSec: number;
}

export interface ReportBundle {
  from: LocalDate;
  to: LocalDate;
  calibration: CalibrationReport;
  projectWeeks: ProjectWeekRow[];
  weeklyTargets: WeeklyTargetRow[];
  totalPlannedSec: number;
  totalTrackedSec: number;
  streakDays: number;
}

export interface SearchHit {
  kind: string;
  id: string;
  title: string;
  subtitle: string | null;
  matchFrom: number | null;
  matchTo: number | null;
}

export interface SearchResults {
  query: string;
  hits: SearchHit[];
}

export interface UndoToken {
  entity: string;
  id: string;
  label: string;
  at: Millis;
}

export interface DeletedRow {
  entity: string;
  id: string;
  title: string;
  deletedAt: Millis;
}

export interface CaptureChip {
  kind: "project" | "tag" | "estimate" | "priority" | "due";
  raw: string;
  display: string;
  from: number;
  to: number;
  /** §4.4 rule 7 — an unknown project renders as `#newproj (create)`. */
  creates: boolean;
}

export interface CapturePreview {
  raw: string;
  title: string;
  projectName: string | null;
  projectId: string | null;
  projectCreates: boolean;
  tags: string[];
  estimateSec: number | null;
  priority: number;
  dueDate: LocalDate | null;
  dueAt: Millis | null;
  chips: CaptureChip[];
}

export interface IntegrityReport {
  quickCheck: string;
  foreignKeyViolations: number;
  orphanOpenSessions: number;
  cachesRepaired: number;
  blocksCrossingMidnight: number;
  pageCount: number;
  dbBytes: number;
  checkedAt: Millis;
}

export type CollisionPolicy = "overlap" | "push" | "shrink";
export type IdleActionKind = "keep" | "discard" | "assignToBreak";
export type RecoveryActionKind = "trimToHeartbeat" | "keepAll" | "discard";

/** Errors cross IPC as `{ code, message }` — branch on the code, show the sentence. */
export interface WireError {
  code: string;
  message: string;
}

export interface NewTask {
  title: string;
  projectId?: string | null;
  parentId?: string | null;
  estimateSec?: number | null;
  dueDate?: LocalDate | null;
  dueAt?: Millis | null;
  priority?: number | null;
  energy?: string | null;
  isRollover?: boolean;
  tags?: string[];
}

export interface TaskPatch {
  title?: string;
  projectId?: string | null;
  estimateSec?: number | null;
  dueDate?: LocalDate | null;
  dueAt?: Millis | null;
  priority?: number;
  energy?: string | null;
  sortRank?: number;
  isRollover?: boolean;
  tags?: string[];
}

export interface NewBlock {
  taskId?: string | null;
  label?: string | null;
  startsAt: Millis;
  durationSec: number;
  tz: string;
  isFixed?: boolean;
  /** Present means "make this a series" (§2.3, P2). */
  rrule?: string | null;
}

export interface TaskQuery {
  projectId?: string | null;
  tag?: string | null;
  text?: string | null;
  scope?: "open" | "done" | "all" | "deleted";
  includeSubtasks?: boolean;
  limit?: number;
  offset?: number;
}

// ─── life time and the unified day (Plan Rev 3 §7, §8.1) ───────────────

export type AreaKind = "core" | "entertainment" | "rest" | "other";

export interface LifeAreaRow {
  id: string;
  name: string;
  colour: string;
  kind: AreaKind;
  monthlyTargetSec: number | null;
  sortRank: number;
  /** Built-ins archive but never delete — an imported workbook maps onto them. */
  isBuiltin: boolean;
  isArchived: boolean;
  monthTrackedSec: number;
}

export interface LifeEntryRow {
  id: string;
  lifeAreaId: string;
  areaName: string;
  areaColour: string;
  areaKind: AreaKind;
  label: string | null;
  startedAt: Millis;
  endedAt: Millis;
  localDate: LocalDate;
  tz: string;
  /** Accounted for, but nothing recorded about it. */
  isPrivate: boolean;
  note: string | null;
}

export interface NewLifeEntry {
  lifeAreaId: string;
  label?: string | null;
  startedAt: Millis;
  endedAt: Millis;
  tz: string;
  isPrivate?: boolean;
  note?: string | null;
  /** Clears whatever confirmed record already covers the interval. Destructive. */
  replaceExisting?: boolean;
}

/** Work records only. `life_entry` has no counterpart, by design. */
export type Contribution = "none" | "attend" | "support" | "own" | "assist";

export const CONTRIBUTIONS: { value: Contribution; label: string; hint: string }[] = [
  { value: "none", label: "None", hint: "Work, with no contribution mode recorded" },
  { value: "attend", label: "Attend", hint: "You were present" },
  { value: "support", label: "Support", hint: "You helped someone else's work" },
  { value: "own", label: "Own", hint: "The outcome was yours" },
  { value: "assist", label: "Assist", hint: "You did part of it, someone else led" },
];

/** Exactly one owner per segment — two owners would be two durations. */
export type SlotOwner =
  | {
      kind: "life";
      entryId: string;
      areaId: string;
      areaName: string;
      areaColour: string;
      areaKind: AreaKind;
      label: string | null;
      isPrivate: boolean;
    }
  | {
      kind: "work";
      sessionId: string;
      taskId: string;
      taskTitle: string;
      projectId: string | null;
      projectColour: string | null;
      contribution: Contribution | null;
    }
  | { kind: "observed"; appId: string; domain: string | null; category: string | null }
  | { kind: "idle" }
  | { kind: "empty" };

export interface DaySegment {
  from: Millis;
  to: Millis;
  owner: SlotOwner;
  /** Evidence, not duration — see `attach_evidence` in day.rs. */
  evidence: AppTotal[];
  /** Confirmed work with entertainment observed inside it. */
  hasDistraction: boolean;
}

export interface DayPlan {
  blockId: string;
  title: string;
  projectColour: string | null;
  startsAt: Millis;
  durationSec: number;
  trackedSec: number;
  driftSec: number;
  driftState: DriftState;
  isFixed: boolean;
  seriesId: string | null;
  /** Work, an entertainment window, or life — so a planned two hours of
   *  television does not read as two hours of missing work. */
  intent: BlockIntent;
}

export type SlotState =
  | "empty"
  | "plannedNotStarted"
  | "confirmedWork"
  | "confirmedLife"
  | "private"
  | "observedOnly"
  | "idle";

export interface DaySlot {
  index: number;
  startsAt: Millis;
  endsAt: Millis;
  segments: DaySegment[];
  plans: DayPlan[];
  state: SlotState;
}

export interface AreaTotal {
  areaId: string;
  name: string;
  colour: string;
  kind: AreaKind;
  seconds: number;
  monthlyTargetSec: number | null;
}

export interface DayProjectTotal {
  projectId: string | null;
  name: string;
  colour: string | null;
  seconds: number;
}

export interface DayTotals {
  daySec: number;
  plannedSec: number;
  /** The part of `plannedSec` plotted as an entertainment window — an evening
   *  you *meant* to spend on a film. A subset, not an extra bucket. */
  plannedEntertainmentSec: number;
  confirmedWorkSec: number;
  confirmedLifeSec: number;
  /** A subset of `confirmedLifeSec` — the workbook reports sleep on its own line. */
  sleepSec: number;
  privateSec: number;
  observedOnlySec: number;
  idleSec: number;
  emptySec: number;
  entertainmentSec: number;
  /** The part of `entertainmentSec` that fell inside a plotted entertainment
   *  window. `entertainmentSec` minus this is the unplanned part; the two
   *  reconcile by construction. */
  entertainmentInWindowSec: number;
  /** Overlaps the layers above on purpose — a different question. */
  pcSec: number;
  byArea: AreaTotal[];
  byProject: DayProjectTotal[];
  byApp: AppTotal[];
}

export interface DayView {
  localDate: LocalDate;
  tz: string;
  slotMinutes: number;
  startsAt: Millis;
  endsAt: Millis;
  slots: DaySlot[];
  segments: DaySegment[];
  totals: DayTotals;
  isReconciled: boolean;
  isToday: boolean;
  now: Millis;
  fragmentation: Fragmentation;
}

// ─── the month (Plan Rev 3 §8.5, wireframe screen 3) ───────────────────

export interface MonthDay {
  localDate: LocalDate;
  dayOfMonth: number;
  daySec: number;
  confirmedWorkSec: number;
  confirmedLifeSec: number;
  sleepSec: number;
  privateSec: number;
  observedOnlySec: number;
  idleSec: number;
  emptySec: number;
  entertainmentSec: number;
  /** The part of `entertainmentSec` that happened inside a plotted window.
   *  The rest is unplanned. */
  entertainmentInWindowSec: number;
  /** Time plotted as an entertainment window. Compare with
   *  `entertainmentSec`, which is what actually happened. */
  plannedEntertainmentSec: number;
  isReconciled: boolean;
  /** The day has ended. A future day is not "unreviewed", it just hasn't come. */
  hasHappened: boolean;
  /** 0–1. What the data-quality heatmap shades by. */
  accountedRatio: number;
}

export interface MonthFinding {
  key: string;
  label: string;
  /** Pre-formatted: "+38%" and "14h 20m" are different kinds of number. */
  value: string;
  detail: string | null;
  isWarning: boolean;
}

export interface MonthView {
  month: string;
  label: string;
  from: LocalDate;
  to: LocalDate;
  tz: string;
  days: MonthDay[];
  /** The Day view's shape, summed — so the two can never disagree. */
  totals: DayTotals;
  accountedRatio: number;
  /** The pair that agree with `accountedRatio` — `totals` covers the whole
   *  month including days that have not arrived. */
  elapsedSec: number;
  elapsedEmptySec: number;
  unreconciledDays: number;
  findings: MonthFinding[];
}

// ─── Excel export (Plan Rev 3 §10, wireframe screen 5) ─────────────────

// ─── workbook import (M13, §4.8) ───────────────────────────────────────

/** One sheet, described rather than interpreted. `null` fields are findings,
 *  not failures — the sheet genuinely has no header row Fruit can see. */
export interface SheetShape {
  name: string;
  rows: number;
  cols: number;
  headerRow: number | null;
  timeCol: number | null;
  dayColumns: ImportDayColumn[];
  firstMinute: number | null;
  slotMinutes: number | null;
  /** Every distinct label, most slots first. Its length is the honest measure
   *  of how much work the mapping step is. */
  labels: LabelCount[];
}

export interface ImportDayColumn {
  col: number;
  header: string;
  dayOfMonth: number;
}

export interface LabelCount {
  label: string;
  /** Slots, not hours: hours need the slot length, which is a mapping decision
   *  rather than a fact about the file. */
  slots: number;
}

export interface WorkbookInspection {
  path: string;
  sheets: SheetShape[];
}

/**
 * What a label means. Four answers, and one of them is "nothing" — the
 * alternative to an explicit ignore is an implicit one, and §4.8's "no silent
 * loss" is a rule about silence.
 */
export type ImportTarget =
  | { kind: "ignore" }
  | { kind: "work"; taskId?: string | null }
  | { kind: "life"; lifeAreaId: string }
  | { kind: "private" };

export interface ImportRule {
  label: string;
  target: ImportTarget;
}

export interface ImportMapping {
  sheet: string;
  headerRow: number;
  timeCol: number;
  columns: ImportDayColumn[];
  slotMinutes: number;
  /** `YYYY-MM`. Empty blocks the import: a sheet headed "1 … 31" does not say
   *  which month it is, and picking one for the user is picking wrong. */
  month: string;
  tz: string;
  rules: ImportRule[];
  replaceExisting: boolean;
}

export interface ImportPreview {
  sheet: string;
  month: string;
  tz: string;
  slotMinutes: number;
  totalSec: number;
  /** Time a rule says to drop. Reported, because dropping it was a decision. */
  ignoredSec: number;
  days: ImportDay[];
  unmapped: LabelCount[];
  conflictingDates: LocalDate[];
  /** Everything between this preview and a commit, in sentences. Empty means
   *  the import will go through. */
  blocking: string[];
}

export interface ImportDay {
  localDate: LocalDate;
  slots: number;
  seconds: number;
  existingSec: number;
  /** Signed: "12h of variance" without a direction is unusable. */
  varianceSec: number;
  conflicts: boolean;
}

export interface ImportResult {
  batchId: string;
  month: string;
  sessionsWritten: number;
  lifeEntriesWritten: number;
  recordsReplaced: number;
  totalSec: number;
}

export interface ImportBatch {
  id: string;
  sourcePath: string;
  sheet: string;
  month: string;
  tz: string;
  sessionsWritten: number;
  lifeEntriesWritten: number;
  createdAt: Millis;
}

// ─── the Monday-morning report (W9) ────────────────────────────────────

/** Everything the weekly report says, in the order it says it. */
export interface WeekReport {
  headline: WeekHeadline;
  review: WeekReview;
  divergence: WeekDivergence | null;
  unlabelled: UnlabelledRow[];
}

/**
 * *"The most important information is right at the top — the Work hours from
 * last week and the breakdown into categories."* This is that sentence and
 * nothing else; anything that creeps in here pushes the two figures the reader
 * came for below the fold.
 */
export interface WeekHeadline {
  workSec: number;
  categories: WeekCategory[];
  /** The week has ended. False means it must not call itself "last week". */
  isComplete: boolean;
}

export interface WeekCategory {
  name: string;
  seconds: number;
  /** Carried rather than computed here: the rows partition the week, and a
   *  percentage against the wrong denominator is how that stops being true. */
  share: number;
}

export type DivergenceKind = "overrun" | "unplannedEntertainment";

export interface WeekDivergence {
  localDate: LocalDate;
  kind: DivergenceKind;
  seconds: number;
  detail: string;
}

/** A report waiting to be read. `null` means there is nothing to say. */
export interface WeekReportDue {
  week: string;
  from: LocalDate;
  to: LocalDate;
  headline: WeekHeadline;
  /** Where the file went, if one exists. `null` means it can be written. */
  writtenTo: string | null;
}

export interface WeekReportResult {
  path: string;
  week: string;
  headline: string;
  sheets: string[];
}

export interface ExcelOptions {
  includeObserved: boolean;
  includeUnaccounted: boolean;
  /** Off by default. Private *duration* is always exported; this names the area. */
  includePrivateLabels: boolean;
}

export interface ExcelVariance {
  measure: string;
  appSec: number;
  sheetSec: number;
  varianceSec: number;
}

export interface ExcelCell {
  label: string;
  /** work · life · entertainment · rest · observed · gap · private */
  kind: string;
  colour: string | null;
}

export interface ExcelPreview {
  month: string;
  label: string;
  fileName: string;
  dayHeaders: string[];
  slotLabels: string[];
  /** `rows[slot][day]` — the whole month matrix, blanks included. */
  rows: ExcelCell[][];
  variances: ExcelVariance[];
  unreconciledDays: number;
  sourceNote: string;
}

export interface ExcelExportResult {
  path: string;
  sheets: string[];
  rowsWritten: number;
  variances: ExcelVariance[];
}
