-- 0002_tracked_cache.sql — explicit, rebuildable caches (spec §6.4 cache policy).
-- The views remain the truth; these rows are written inside the same transaction
-- as every session mutation and can be regenerated by rebuild_tracked_caches().

CREATE TABLE block_tracked_cache (
  block_id    TEXT PRIMARY KEY REFERENCES scheduled_block(id) ON DELETE CASCADE,
  tracked_sec INTEGER NOT NULL DEFAULT 0 CHECK (tracked_sec >= 0),
  computed_at INTEGER NOT NULL
);

CREATE TABLE task_tracked_cache (
  task_id     TEXT PRIMARY KEY REFERENCES task(id) ON DELETE CASCADE,
  tracked_sec INTEGER NOT NULL DEFAULT 0 CHECK (tracked_sec >= 0),
  computed_at INTEGER NOT NULL
);

INSERT INTO block_tracked_cache (block_id, tracked_sec, computed_at)
SELECT block_id, tracked_sec, 0 FROM block_tracked;

INSERT INTO task_tracked_cache (task_id, tracked_sec, computed_at)
SELECT task_id, tracked_sec, 0 FROM task_tracked;
